# Generated by Django 4.2.2 on 2023-08-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('type', models.IntegerField(choices=[(1, 'Type 1'), (2, 'Type 2')])),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Not active')])),
            ],
        ),
    ]
