# Generated by Django 4.2.2 on 2023-08-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='type',
            field=models.IntegerField(choices=[(1, 'Chair'), (2, 'Table'), (3, 'Tent'), (3, 'Food'), (3, 'Drink')]),
        ),
    ]
