# Generated by Django 4.2.2 on 2023-08-24 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(1, 'Type 1'), (2, 'Type 2')])),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
