# Generated by Django 4.2.2 on 2023-08-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guests',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Completed'), (3, 'Paid')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(1, 'Birthday'), (2, 'Wedding')]),
        ),
    ]
